services:
    redis:
        image: redis:latest
        container_name: redis
        restart: always

    qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        restart: always

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: db

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: 12345678
        command: server --console-address ":9001" /data

    celery:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                VERSION: 3.12
        env_file:
            - ./.env
        container_name: celery
        restart: always
        depends_on:
            - redis
        command: celery -A src worker -E --loglevel=info

    elastic-search:
        image: elasticsearch:8.8.0
        container_name: elastic-search
        restart: always
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - logger.level=error
            - ES_JAVA_OPTS=-Xms512m -Xmx512m

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                VERSION: 3.12
        env_file:
            - ./.env
        container_name: backend
        restart: always
        depends_on:
            - postgres
            - qdrant
            - minio
            - redis
            - elastic-search
            - celery
        command: ["python", "app.py"]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://backend:8000"]
            interval: 5s
            timeout: 10s
            retries: 5

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                NODE_VERSION: 22
        container_name: frontend
        restart: always
        depends_on:
            - backend

    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "3000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend
