services:
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    qdrant:
        image: qdrant/qdrant:latest
        container_name: qdrant
        restart: always
        ports:
            - "6333:6333"
            - "6334:6334"

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./minio_storage:/data
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: 12345678
        command: server --console-address ":9001" /data
