name: Frontend (install and build)

on:
    push:
        branches: ["main", "hien_dev"]
    pull_request:
        branches: ["main", "hien_dev"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - uses: actions/checkout@v4
            - name: Run
              run: |
                  cd frontend/

                  export NEXT_PUBLIC_BASE_API_URL=http://localhost:8000

                  npm install

                  npm run build
