name: Production-Ready

on:
    push:
    pull_request:
        branches: ["main"]

jobs:
    build-production:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: docker compose build
              run: |
                  cp .env.production .env
                  cp .env.production frontend/.env.local
                  docker compose up -d --build

            - name: Sleep for 60 seconds
              uses: jakejarvis/wait-action@master
              with:
                  time: "60"

            - name: List all docker images
              run: |
                  docker images

            - name: List all docker containers
              run: |
                  docker ps -as

            - name: logs backend service
              run: |
                  docker logs backend
